[project]
name = "odoo-addons-oca-l10n-finland"
version = "18.0.20250630.0"
dependencies = [
    "odoo-addon-l10n_fi_banks==18.0.*",
    "odoo-addon-l10n_fi_edicode==18.0.*",
    "odoo-addon-l10n_fi_sale_refund_payment_reference==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
